import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='flex justify-between py-4 px-10 border-gray-200 border-b-2'>
        <div className='font-bold'>
          Where in the world?
        </div>
        <button>
          🌜  Dark mode
        </button>
      </header>
      {children}
      </body>
    </html>
  )
}
